packages:
  - apps/*
  - services/*
  - packages/*

allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/linux-arm64': true
